### PR TITLE
autotools to meson

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**

### CODE REVIEW

**Comment by gnumdk** [comment]
Lollypop portal is not executable

**Comment by bil-elmoussaoui** [comment]
It's installed correctly on libexec so it's not executable or there's something i'm missing?

**Comment by gnumdk** [comment]
It need to be executable.
«/usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts.»
It does not mean not executable I guess, no?

**Comment by bil-elmoussaoui** [comment]
Makes sense. I will create a PR soon. the configure_file from meson doesn't provide the possibility to modify the file permissions. So maybe just making the python file executable in the repository? 
This way the output file will also be executable. Meson build system preserve the file permissions

**Comment by gnumdk** [comment]
python file is created by meson.

**Comment by gnumdk** [comment]
The dbus file is installed in/usr/dbus-1/services instead of /usr/share/dbus-1/services

**Comment by bil-elmoussaoui** [comment]
Alright, so i've to make the file executable and install the dbus file in /usr instead of /usr/share ?

**Comment by gnumdk** [comment]
no, here it's installed in /usr/dbus-1, the good path is /usr/share

**Comment by bil-elmoussaoui** [comment]
Ah alright, i will fix that right now :)

**Pull request merged**
